[package]
name                  = "sdf-offline"
version               = { workspace = true }
edition               = { workspace = true }

[dependencies]
chacha20              = { workspace = true }
dirs                  = { workspace = true }
error-location        = { workspace = true }
lz4_flex              = { workspace = true }
serde                 = { workspace = true }
serde_json            = { workspace = true }
sha2                  = { workspace = true }
soul-attributes       = { workspace = true }
thiserror             = { workspace = true }
toml                  = { workspace = true }
toml_edit             = { workspace = true }

[lints]
workspace             = true
